---
title: Mariemont Community Church
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  sermons:
    title: Sermons
    output: true
  staff:
    title: Staff
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: sermons
  values:
    layout: page-sermon
    series: ''
    week: ''
    sermon_date: ''
    sermon_bg: "/uploads/sermon_bg.jpg"
    speaker: ''
    bible_text: ''
    excerpt: ''
    audio_file: ''
    video_url: ''
    brochure_file: ''
    thumbnail_image: ''
    is_featured: false
- scope:
    path: ''
    type: pages
  values:
    bg_color: ''
    hero_image: ''
    hasHero: false
    hasDownload: false
    download:
      file: 
      info: 
      cta: 
    heading: ''
    lead_in: ''
email: mark@mariemontchurch.org
description: We are a growing community of families in East Cincinnati united by our
  commitment to follow Jesus.
baseurl: 
url: http://mariemontchurch.org
markdown: kramdown
highlighter: rouge
plugins_dir: plugins
plugins:
- jekyll-seo-tag
port: 7000
permalink: "/:categories/:title/"
